### ISSUE TITLE
Can this tool monitor visual differences of a page?

### ISSUE THREAD

**Issue by fishfree** [SR-G/watchthatpage#4]
I find this tool uses wkhtml2pdf to generate images, so does it support to monitor visual differences of a page?
Under some situations, monitoring DOM differences is not enough. For example, some crackers replace a same-name image file.

**Comment by SR-G** [comment]
Hello.
This tool is really about comparing (text) content from web pages (in order to detect through that analysis the differences over time).
wkhtml2image (or anything else) may be used on top of that, in order to attach some screenshots to the generated notification mails, but these (optional) images are just for the reports and aren't used in order to calculate the differences.
